spring:
    profiles:
        activate:
            on-profile: dev

    datasource:
        url: jdbc:h2:mem:deploy;MODE=MYSQL
        #      url: jdbc:h2:tcp://localhost/~/testdb;MODE=MYSQL
        username: user
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                default_batch_fetch_size: 1000
                dialect: org.hibernate.dialect.MySQL57Dialect
                dialect.storage_engine: innodb
        defer-datasource-initialization: true

    h2:
        console:
            enabled: true
            path: '/h2-console'

    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        listener:
            direct:
                prefetch: 1
            simple:
                prefetch: 1

rabbitmq:
    queue.name: rabbit.queue
    exchange.name: rabbit.exchange
    routing.key: rabbit.key

management:
    endpoint:
        health:
            show-details: always
