name: cd-staging

on:
  push:
    branches: [ "staging" ]

permissions:
  contents: read

jobs:
  deploy:
    name: CD / Deploy ECR, ECS
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PWD }}
          docker build -t sangwoo98/deploy .
          docker push sangwoo98/deploy
