name: cd-staging

on:
  push:
    branches: [ "staging" ]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy ECR, ECS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: build/libs/

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PWD }}
          docker build -t sangwoo98/deploy .
          docker push sangwoo98/deploy
